version: '3'

services:
  app:
    build: '.'
    restart: on-failure
    ports:
      - '${HOST_PORT}:${PORT}'
    env_file:
        - .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${PORT}/ping" ]
      interval: 2m
      timeout: 10s
      retries: 3
