name: Build test
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: build a binary
        run: go build ./cmd/api
      - name: run tests
        run: go test ./... -v
