name: Tests
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: verify dependencies
        run: go mod verify

      - name: build a binary
        run: go build -v ./...

      - name: run tests
        run: go test -race ./...
